In [7]:
import numpy as np

In [8]:
#function that returns derivative when delta needs to be found , sigmoid activation function otherwise

def nonlin(x,deriv=False):
    if deriv == True: 
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))    

In [9]:
X = np.genfromtxt('filename_inputs.csv', skip_headers = 1)
# assuming no. of features = n , no. of datapoints = m                
y = np.genfromtxt('finename_outputs.csv', skip_headers = 1)

np.random.seed(1)

# Randomly initialize our weights with mean 0
W1 = 2*np.random.random((n, 3)) - 1  #  weights between layer 0 and layer 1 , shape = n*5 
#hidden layer 1 nodes = 3
W2 = 2*np.random.random((3, 5)) - 1  #  weights between layer 1 and layer 2
#hidden layer 2 nodes = 5
W3 = 2*np.random.random((5, 1)) - 1  #  weights between layer 2 and layer 3
#optput layer nodes = 1

In [10]:
#training steps = 100
learning_rate = 0.01
for j in range(100):
    
    
    # forward_propogation
    # Feed forward through layers 0, 1, 2, 3
    layer0 = X                           # input layer
    layer1 = nonlin(np.dot(layer0, W1))  # first hidden layer
    layer2 = nonlin(np.dot(layer1, W2))  # second hidden layer
    layer3 = nonlin(np.dot(layer2, W3))  # output layer
    
    
    #back_propogation
    # Error: How much did we miss the target value?
    # Delta: In what direction is the target value? Were we really sure? If so, don't change too much.
    
    layer3_error = y - layer3
    layer3_delta = layer3_error * nonlin(layer3, deriv=True) # "deriv=True" coz we're interested in the gradient

    layer2_error = np.dot(layer3_delta, W3.T)  # l3_delta.dot(syn_23.T)
    layer2_delta = layer2_error * nonlin(layer2, deriv=True)

    layer1_error = np.dot(layer2_delta, W2.T)
    layer1_delta = layer1_error * nonlin(layer1, deriv=True)
    
    # Update weights
    # Gradient_descent
    
    W3 += learning_rate*layer2.T.dot(layer3_delta)
    W2 += learning_rate*layer1.T.dot(layer2_delta)
    W1 += learning_rate*layer0.T.dot(layer1_delta)
    
    if (j% 10) == 0:
        print("Error: {0:.4f}".format((np.mean(np.abs(layer3_error)))))
# End of for loop.

Error: 0.0328
Error: 0.0328
Error: 0.0328
Error: 0.0328
Error: 0.0328
Error: 0.0328
Error: 0.0328
Error: 0.0328
Error: 0.0328
Error: 0.0328


In [11]:
#=======================#
# Print the syn weights #
#=======================#
np.set_printoptions(precision=4)
print('\n\nW1 (shape:%s): \n%s' % (W1.shape, W1))
print('\nW2 (shape:%s): \n%s' % (W2.shape, W2))
print('\nW3 (shape:%s): \n%s' % (W3.shape, W3))



W1 (shape:(3, 5)): 
[[ 0.1349  0.3814  0.7938 -1.6349  0.5433]
 [-0.4631 -0.6279  0.9332 -1.229   1.0354]
 [ 0.1775  0.2656  0.3639  0.8501 -0.2893]]

W2 (shape:(5, 7)): 
[[ 0.3532 -0.3997  0.1651 -0.8816 -0.5967  0.5916  1.0111]
 [-0.3719  0.1904  0.7797  0.6421 -0.8199 -0.9324 -0.5957]
 [ 2.5016 -2.4496  0.8267  1.8804 -0.5309  1.904  -0.9236]
 [-2.0596  2.2014 -2.2717 -1.4309  1.7921 -1.5799  0.5289]
 [ 0.7062 -0.9787 -0.0205  0.8386 -0.4563 -0.316  -0.7602]]

W3 (shape:(7, 1)): 
[[-5.1353]
 [ 4.3902]
 [-3.3595]
 [-3.4473]
 [ 1.8182]
 [-4.1351]
 [ 1.5077]]


In [12]:

# Predict #

def pred(data):
    for syn in [syn_01, syn_12, syn_23]:
        data = nonlin(np.dot(data, syn))
    return data

X_test = np.genfromtxt('your_test_file.csv', skip_headers = 1)
print('\n\nPredictions for: %s' % X_test.tolist())
print(pred(X_test))

X_test = np.array([[0,0,1], [1,1,1]])
print('\nPredictions for: %s' % X_test.tolist())
print(pred(X_test))




Predictions for: [[0, 1, 1], [1, 0, 1]]
[[ 0.9675]
 [ 0.9678]]

Predictions for: [[0, 0, 1], [1, 1, 1]]
[[ 0.0202]
 [ 0.0463]]
